# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - conda-base
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update sync
      run: |
        pip install update
        pip install pandas requests
        python pull-data.py


    # container: docker.pkg.github.com/library-usage/library-sync/sync:latest
    # steps:
    #   - run: |
    #       python 
    #       cd ~/
    #       git clone https://github.com/library-usage/library-sync.git
    #       ls
    #       python pull-library-data.py

